# Generated by Django 5.0.6 on 2024-06-10 00:13

import datetime
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=140)),
                ('last_name', models.CharField(max_length=140)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('course_title', models.CharField(max_length=140)),
                ('course_major', models.CharField(max_length=140)),
                ('course_minor', models.CharField(default='None', max_length=140)),
                ('course_duration', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('enrolled', models.BooleanField(default=False)),
                ('enrolment_date', models.DateField(default=datetime.date.today)),
                ('enrolment_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['last_name'],
            },
        ),
    ]
